HomeRealm_Project/Controllers/SettingController.cs
using HomeRealm_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeRealm_Project.Controllers
{
    public class SettingController : Controller
    {
        // GET: Setting
        public ActionResult Index()
        {
            SettingModel CurrentUser;
            int id = int.Parse(Session["iduser"].ToString());
            using (MydbContext db = new MydbContext()) {
                CurrentUser = new SettingModel() { user = db.Users.Find(Session["iduser"]), host = db.Hosts.Where(d => d.User.Id == id).FirstOrDefault() };
                if (CurrentUser.user is null) {
                    return Redirect("Home");
                }
            
            }
            return View(CurrentUser);
        }
        [HttpPost]
        
        public ActionResult Submitchange(FormCollection formCollection)
        {
            int id = int.Parse(Session["iduser"].ToString());
            MydbContext db = new MydbContext();
            // Retrieve the current user from the database
            var currentUser = db.Users.FirstOrDefault(u => u.Id == id);

            // Update the user attributes based on the form data
            currentUser.FirstName = formCollection["Firstname"];
            currentUser.LastName = formCollection["Lastname"];
            currentUser.Email = formCollection["Email"];
           

            // Check if the password fields are not empty
            if (!string.IsNullOrEmpty(formCollection["oldpass"]) && !string.IsNullOrEmpty(formCollection["newpass"]) && !string.IsNullOrEmpty(formCollection["newpassC"]))
            {
                string oldPassword = formCollection["oldpass"];
                string newPassword = formCollection["newpass"];
                string confirmPassword = formCollection["newpassC"];

               if(oldPassword== currentUser.Password && newPassword== confirmPassword) { 
                // Update the user's password
                currentUser.Password = newPassword;
            }
            }

            // Save the changes to the database
            db.SaveChanges();

            // Redirect to a success page or return a success message
            return RedirectToAction("Index");
        }






    }
}

HomeRealm_Project/Views/Setting/Index.cshtml
@using HomeRealm_Project.Models
@model SettingModel
@{
    ViewBag.Title = "Index";
}
<form method="post" action=@Url.Action("Submitchange", "Setting") enctype="multipart/form-data">
    <div class="container light-style flex-grow-1 container-p-y">

        <h4 class="font-weight-bold py-3 mb-4">
            Account settings
        </h4>

        <div class="card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action active" data-toggle="list" href="#account-general">General</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-change-password">Change password</a>
                        @if (Session["rule"] == "host")
                        {<a class="list-group-item list-group-item-action" data-toggle="list" href="#account-info">Info</a>}
                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-notifications">Notifications</a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">

                            <div class="card-body media align-items-center">
                                <img src="~/images/ProfilePic/@Model.user.Picture" alt="" class="d-block ui-w-80">
                                <div class="media-body ml-4">
                                    <label class="btn btn-outline-primary">
                                        Upload new photo
                                        <input type="file" class="account-settings-fileinput" name="upldatedPic">
                                    </label> &nbsp;
                                    <button type="button" class="btn btn-default md-btn-flat">Reset</button>

                                    <div class="text-light small mt-1">Allowed JPG PNG. Max size of 800K</div>
                                </div>
                            </div>
                            <hr class="border-light m-0">

                            <div class="card-body">
                                <div class="form-group">
                                    <label class="form-label">First Name</label>
                                    <input type="text" class="form-control mb-1" name="Firstname" value="@Model.user.FirstName">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Family Name</label>
                                    <input type="text" class="form-control" name="Lastname" value="@Model.user.LastName">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">E-mail</label>
                                    <input type="text" class="form-control mb-1" value="@Model.user.Email">
                                    <div class="alert alert-warning mt-3">
                                        Your email is not confirmed. Please check your inbox.<br>
                                        <a href="javascript:void(0)">Resend confirmation</a>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Company</label>
                                    <input type="text" class="form-control" value="Company Ltd.">
                                </div>
                            </div>

                        </div>
                        <div class="tab-pane fade" id="account-change-password">
                            <div class="card-body pb-2">

                                <div class="form-group">
                                    <label class="form-label">Current password</label>
                                    <input type="password" name="oldpass" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label class="form-label">New password</label>
                                    <input type="password" name="newpass" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label class="form-label">Repeat new password</label>
                                    <input type="password" name="newpassC" class="form-control">
                                </div>

                            </div>
                        </div>
                        @if (Session["rule"] == "host")
                        {
                            <div class="tab-pane fade" id="account-info">
                                <div class="card-body pb-2">

                                    <div class="form-group">
                                        <label class="form-label">Bio</label>
                                        <textarea class="form-control" rows="5">@Model.host.Bio</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Birthday</label>
                                        <input type="text" class="form-control" value="@Model.host.Birthday">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Country</label>
                                        <select class="custom-select">
                                            <option>USA</option>
                                            <option selected="">Canada</option>
                                            <option>UK</option>
                                            <option>Germany</option>
                                            <option>France</option>
                                        </select>
                                    </div>


                                </div>
                                <hr class="border-light m-0">
                                <div class="card-body pb-2">

                                    <h6 class="mb-4">Contacts</h6>
                                    <div class="form-group">
                                        <label class="form-label">Phone</label>
                                        <input type="text" class="form-control" value="@Model.user.PhoneNumber">
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">Website</label>
                                        <input type="text" class="form-control" value="">
                                    </div>

                                </div>

                            </div>
                        }
                        <div class="tab-pane fade" id="account-notifications">
                            <div class="card-body pb-2">

                                <h6 class="mb-4">Activity</h6>

                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" class="switcher-input" checked="">
                                        <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                        <span class="switcher-label">Email me when someone comments on my article</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" class="switcher-input" checked="">
                                        <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                        <span class="switcher-label">Email me when someone answers on my forum thread</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" class="switcher-input">
                                        <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                        <span class="switcher-label">Email me when someone follows me</span>
                                    </label>
                                </div>
                            </div>
                            <hr class="border-light m-0">
                            <div class="card-body pb-2">

                                <h6 class="mb-4">Application</h6>

                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" class="switcher-input" checked="">
                                        <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                        <span class="switcher-label">News and announcements</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" class="switcher-input">
                                        <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                        <span class="switcher-label">Weekly product updates</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" class="switcher-input" checked="">
                                        <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                        <span class="switcher-label">Weekly blog digest</span>
                                    </label>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="text-right mt-3">
            <button type="submit" class="btn btn-primary">Save changes</button>&nbsp;
            <button type="reset" class="btn btn-default">Cancel</button>
        </div>

    </div>
</form>
<link href="~/Content/CSS/Setting.css" rel="stylesheet" />