HomeRealm_Project/Controllers/LoginController.cs
using HomeRealm_Project.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeRealm_Project.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult SubmitLogin(FormCollection  FC)
        {
            string pass = FC["Password"];
            string email = FC["Email"];
            string path = Server.MapPath("~/Admins.json");
            AdminService a = new AdminService(path);
            if (a.AdminExists(email,pass))
            {
                Session["Admin"] = "Admin";
                return RedirectToAction("Index", "Dashboard");
            }
            using (var db = new MydbContext()) {
                var USER = db.Users.FirstOrDefault(user => user.Password == pass && user.Email == email);
                if(USER != null)
                {
                   
                    Session["iduser"] = USER.Id; 
                    Session["usermail"] = USER.Email;
                    if (db.Hosts.Find(USER.Id) is null) {
                        Session["rule"] = "user";
                    }else
                    {
                        Session["rule"] = "host";
                    }

                }
            }
                

            return RedirectToAction("Index", "Home");
        }
    }
}

HomeRealm_Project/Controllers/SignUpController.cs
using HomeRealm_Project.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeRealm_Project.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UpgradeToHost()
        {
            return View();
        }
        public ActionResult SubmitHostUpgrade(FormCollection FC)
        {

            HttpPostedFileBase file = Request.Files["IdPic"];

            if (file != null && file.ContentLength > 0)
            {
                int id = (int)Session["iduser"];
                // Do something with the uploaded file
                string fileName = id+ "_" +Path.GetFileName(file.FileName);
                string path = Path.Combine(Server.MapPath("~/images/idPics"), fileName);
                file.SaveAs(path);
                string bio = FC["Bio"];
                
                string country = FC["country"];
                string pic = fileName;

                string dateString = FC["birthday"];
                DateTime date = DateTime.Parse(dateString);

                using (var db = new MydbContext())
                {
                            var u = new Host {User = db.Users.FirstOrDefault(e => e.Id == 1),HostId = 1,Bio = bio,Country=country,IDPicture=pic,Birthday=date,Verified=false};
                            db.Hosts.Add(u);
                            db.SaveChanges();

                }
            }
            
            return RedirectToAction("Index", "Home");

        }
        public ActionResult SubmitSignUp(FormCollection FC)
        {
            string firstname = FC["FirstName"];
            string lastname = FC["LastName"];
            string email = FC["Email"];
            string pass = FC["Password"];
            string num = FC["Phone"];

            

            using (var db = new MydbContext())
            {
                var USER = db.Users.FirstOrDefault(user => user.Email == email);
                if (USER == null)
                {
                    if (firstname == "" || lastname == "" || email == "" || pass == "" || num == "")
                    {
                        ViewBag.Message = "Please write all the required information.";
                       
                    }
                    else {
                        var u = new User { FirstName = firstname, LastName = lastname, Email = email, Password = pass, PhoneNumber = num };
                        db.Users.Add(u);
                        db.SaveChanges();

                        ViewBag.Message = "Welcome new user, account has been created successfully.";
                    }
                   
                }
                else
                {
                    ViewBag.Message = "This email already exists.";
                }
            }

            return View("Index");
        }

    }
}

HomeRealm_Project/Views/Shared/Footer.cshtml
<footer class="bg-light text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Facebook -->
            <a class="btn text-white btn-floating m-1"
               style="background-color: #3b5998;"
               href="https://www.facebook.com/houssin.oussi"
               role="button">
                <i class="fab fa-facebook-f"></i>
            </a>

            <!-- Twitter -->
            <a class="btn text-white btn-floating m-1"
               style="background-color: #55acee;"
               href="#!"
               role="button">
                <i class="fab fa-twitter"></i>
            </a>

            <!-- Google -->
            <a class="btn text-white btn-floating m-1"
               style="background-color: #dd4b39;"
               href="#!"
               role="button">
                <i class="fab fa-google"></i>
            </a>

            <!-- Instagram -->
            <a class="btn text-white btn-floating m-1"
               style="background-color: #ac2bac;"
               href="#!"
               role="button">
                <i class="fab fa-instagram"></i>
            </a>

            <!-- Linkedin -->
            <a class="btn text-white btn-floating m-1"
               style="background-color: #0082ca;"
               href="#!"
               role="button">
                <i class="fab fa-linkedin-in"></i>
            </a>
            <!-- Github -->
            <a class="btn text-white btn-floating m-1"
               style="background-color: #333333;"
               href="#!"
               role="button">
                <i class="fab fa-github"></i>
            </a>


        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgb(0, 0, 0); color: #fff; ">
        &copy; 2023 Home Realm. All rights reserved. | <a href="@Url.Action("Contact", "Home")">Contact us </a>,<a href="@Url.Action("About", "Home")"> About us</a>

    </div>
    <!-- Copyright -->
</footer>

HomeRealm_Project/Views/Shared/HeaderDashboard.cshtml
@using System.Web

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>

    @Scripts.Render("~/bundles/jquery")

    @RenderSection("scripts", required: false)


    <!-- Popper.js library -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap-reboot.min.css">


 
   
   
</head>
<body>
     @if(Session["Admin"] != "Admin")
     {
         Response.Redirect("~/home/index");
     }
    <div class="container-fluid">
        <div class="row flex-nowrap" style="position: fixed; top: 0; width: 100%;">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Admin Menu for HomeRealm</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a href="@Url.Action("index")" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Host Application</span>
                            </a>
                        </li>
                        <li>
                            <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Statistic People</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">users</span>  </a>
                                </li>
                                <li>
                                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Hosts</span>  </a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Statistic properties</span>
                            </a>
                        </li>


                        <li>
                            <a href="#" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers Messages</span>
                            </a>
                        </li>
                    </ul>
                    <hr>
                    <div class="dropdown pb-4">
                        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                            <span class="d-none d-sm-inline mx-1">Admin</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                            
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Sign out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col py-3">
                <main class="site-content">


                    @RenderBody()


                </main>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->


</body>
</html>

HomeRealm_Project/Views/Shared/HostDashboard.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HostDashboard</title>
    <link href="~/Content/CSS/HostDashboard.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
</head>

<!------ Include the above in your HEAD tag ---------->

<body class="home">
    @if (Session["iduser"] is null) {
        Response.Redirect(@Url.Action("index", "Home"), true);

    }
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                <div class="logo">
                    <a hef="home.html">

                        <img src="~/images/homerealm-website-favicon-black.png" />
                    </a>
                </div>
                <div class="navi">
                    <ul>
                        <li class="@((Request.Path == "/ListingMangment") ? "active" : "")"><a href="@Url.Action("Index", "ListingMangment")"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li class="@((Request.Path == "/ListingMangment/Properties") ? "active" : "")"><a href="@Url.Action("viewProperties", "ListingMangment")"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Properties</span></a></li>
                        <li class="@((Request.Path == "/ListingMangment/Bookings") ? "active" : "")"><a href="@Url.Action("ViewBooks", "ListingMangment")"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Bookings</span></a></li>
                        <li class="@((Request.Path == "/ListingMangment/Statistics") ? "active" : "")"><a href="@Url.Action("Index", "ListingMangment")"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Statistics</span></a></li>
                        <li class="@((Request.Path == "/ListingMangment/Reviews") ? "active" : "")"><a href="@Url.Action("Index", "ListingMangment")"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Reviews</span></a></li>

                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                            </nav>
                            <div class="search hidden-xs hidden-sm">
                                <input type="text" placeholder="Search" id="search">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside">
                                <ul class="list-inline header-top pull-right">
                                    <li class="hidden-xs"><a href="@Url.Action("AddHouse", "ListingMangment")" class="add-project" data-toggle="modal" data-target="#add_project">Add Property</a></li>
                                    <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                                    <li>
                                        <a href="#" class="icon-info">
                                            <i class="fa fa-bell" aria-hidden="true"></i>
                                            <span class="label label-primary">3</span>
                                        </a>
                                    </li>
                                    <li class="dropdown">
                                        <div class="navbar-content">

                                            <p class="text-muted small">
                                                @Session["usermail"]
                                            </p>
                                            <div class="divider">
                                            </div>

                                        </div>

                                    </li>
                                    <li> <a href="@Url.Action("Index", "Setting")" class="view btn-sm active">View Profile</a></li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>
                <div class="user-dashboard">
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>



    <!-- Modal -->
    <div id="add_project" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header login-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title">Add Project</h4>
                </div>
                <div class="modal-body">
                    <input type="text" placeholder="Project Title" name="name">
                    <input type="text" placeholder="Post of Post" name="mail">
                    <input type="text" placeholder="Author" name="passsword">
                    <textarea placeholder="Desicrption"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="cancel" data-dismiss="modal">Close</button>
                    <button type="button" class="add-project" data-dismiss="modal">Save</button>
                </div>
            </div>

        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('[data-toggle="offcanvas"]').click(function () {
                $("#navigation").toggleClass("hidden-xs");
            });
        });


    </script>
</body>
</html>

HomeRealm_Project/Views/Shared/_Layout.cshtml
@using System.Web



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home realm (@ViewBag.Title)</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" type="images/x-icon" href="~/images/homerealm.png" />



    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)


    <!-- Popper.js library -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap-reboot.min.css">

    <script src="~/Scripts/js/Logout.js"></script>
    <link href="~/Content/CSS/Main.css" rel="stylesheet" />

</head>
<body>
    <!-- Navbar -->
    <header style="z-index: 9999;">


        <div class="logo" style="width: 100px;">
         <a href="@Url.Action("index", "Home")">   <img src="~/images/homerealm-website-favicon-black.png" alt="logo" style="width: 100%; height: 100%;"> </a>
        </div>


        <section class="search-bar">

            <svg class="search-icon" fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z" />
                <path d="M0 0h24v24H0z" fill="none" />
            </svg>

            <form class="search-form">
                <input type="text" placeholder="Where to?">
            </form>

        </section>


        <ul class="main-nav">
            <li class="help"><a href="@Url.Action("index", "Listing")">Offers</a></li>
            @if (Session["rule"] == "user")
            {
                <li> <a href="@Url.Action("UpgradeToHost", "SignUp")"><button>Become a Host</button> </a></li>
            }
            else if (Session["rule"] == "host")
            {
                <li> <a href="@Url.Action("index", "ListingMangment")"><button>Host mangment</button> </a></li>
            }
            
            @if (Session["iduser"] != null)
            {
                <li>
                    <a href="#">@Session["usermail"]</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Setting")">Settings</a>
                </li>
                <li>
                    @using (Html.BeginForm("DeleteSession", "Home", FormMethod.Post))
                    {
                        <a href="javascript:{}" onclick="this.parentNode.submit(); return false;">Logout</a>
                    }
                </li>

            }
            else
            {   
        <li><a href="@Url.Action("Help", "Home")">Help</a></li>
                <li><a href="@Url.Action("Index", "SignUp")">Sign Up</a></li>
                <li><a href="@Url.Action("Index", "Login")">Login</a></li>
            }


        </ul>
    </header>

    <main class="site-content">


        @RenderBody()







    </main>


    @Html.Partial("Footer")


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="~/Scripts/popper.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>


</body>
</html>


    

HomeRealm_Project/Views/Shared/searching.cshtml
<section class"search-row">
    <form method="post" action="@Url.Action("Search", "Listing")">
        <input class="search-input" type="text" name="location" placeholder="Where to?"></input>


        <div class="checks-input">

            <input class="check-in" type="date" placeholder="Check In" name="checkin" style="margin-right: 10px; width: 200px;" />

            <svg class="right-arrow" xmlns="http://www.w3.org/2000/svg" fill="#000000" height="24" viewBox="0 0 24 24" width="24">
                <path d="M0 0h24v24H0z" fill="none" />
                <path d="M12 4l-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8z" />
            </svg>

            <input class="check-out" type="date" placeholder="Check Out" name="checkout" style="padding: 5px; width: 200px;"/>


        </div>


        <select name="capacity" class="guests">
            <option value="1">1 Guest</option>
            <option value="2">2 Guests</option>
            <option value="3">3 Guests</option>
            <option value="4">4 Guests</option>
            <option value="5">5 Guests</option>
            <option value="6">6 Guests</option>
            <option value="7">7 Guests</option>
            <option value="8">8 Guests</option>
        </select>

        <button type="submit" class="search-btn"> Search </button>
    </form>
</section>